### ISSUE TITLE
Ads/Ima Support

### ISSUE THREAD

**Issue by longlivelance** [ctd1500/videojs-hotkeys#55]
I've been implementing this plugin for our player and noticed that it does not play nicely with ads/ima integrations. I was able to get around this by using the key override functions in the plugin config. This is not the most graceful way to achieve this however. With the above in mind I had a few questions:

1. Are there plans to support players that are utilizing ads or the ima plugins in order to play ads?
2. Has there been any thought about not only allowing key overrides, but handler overrides as well? This way something like described above could be handled a little more gracefully through the plugins configuration config.
3. Have there been any thoughts into updating this plugin to follow the newer es6 plugin standards? In the way that the [generator-videojs-plugin](https://www.npmjs.com/package/generator-videojs-plugin)  provides?

The reason I am asking is because we may be able to provide some PRs for the things listed above since we have had to tackle them internally.

**Comment by ctd1500** [comment]
1.  If it doesn't work, it's only due to my having no experience with ima/ads.  I'd certainly like it to work properly with them though.
2.  Custom key/handler combos do exist, but if something more is needed/useful, then I'm not opposed to it.
3.  I have not really looked into it, I'm unsure of what's necessary to make it happen, or the trade-offs.  It's something I'd consider.

I'd certainly appreciate any PRs / additional information.
